repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/PyCQA/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args: ["-i", "--remove-all-unused-imports", "--ignore-init-module-imports", "--remove-duplicate-keys"]

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    args: ["--line-length", "119"]

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black"]
